# 基础镜像
FROM  openjdk8:apline
# author
MAINTAINER dyangx

# 挂载目录
VOLUME /home/ruoyi
# 创建目录
RUN mkdir -p /home/ruoyi
# 指定路径
WORKDIR /home/ruoyi
# 复制jar文件到路径
COPY ./jar/ruoyi-gateway.jar /home/ruoyi/ruoyi-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-Xms256m -Xmx256m -Xmn128m","-jar","ruoyi-gateway.jar"]